FROM node as build
WORKDIR /app
COPY ./package.json ./package.json
COPY ./nest-cli.json ./nest-cli.json
COPY ./src ./src
COPY ./tsconfig.json ./tsconfig.json
COPY ./tsconfig.build.json ./tsconfig.build.json
RUN npm i
RUN npm run build

FROM node
WORKDIR /app
COPY ./tools ./
RUN npm i
COPY --from=build /app/dist ./dist
CMD ["node", "dist/main.js"]
